version: '3.7'
services:
  api:
    image: api-prod-i
    container_name: api-prod-c
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb+srv://tanchohang:7YTqMBWaUciSyjzY@cluster0.id5shyp.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=def0090101023d3e3db77a864ae028538963352b70da7c2cc63924a0f011b40d0f904fbab3b0d7d2611b9aacf277f8ab2a7d284a822ec9770b0448c6bc06bdcf
      - REFRESH_JWT_SECRET=2721fc5c639824baf8062bc412b81c1ce54a3da55a9c23d13df414865bc1f7d42becff2e55b74ba85be9d93acbb54a8530fb46fc214f54a17bf55d504f1d2483

      - NODE_ENV=production
      - BASE_URL=http://localhost
    user: "node:node"

  client_nginx:
    image: client_nginx-prod-i
    container_name: client_nginx-prod-c
    restart: unless-stopped
    build:
      context: ../keepup-client
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    environment:
      - VITE_API_URL=/api
      - VITE_MODE=production
      - NODE_ENV=production
  # nginx:
  #   depends_on:
  #     - client
  #     - api
  #   image: nginx-prod-i
  #   container_name: nginx-prod-c
  #   restart: unless-stopped
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - 80:80
  #     - 443:443