version: '3.7'
services:
  api:
    image: api-dev-i
    container_name: api-dev-c
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb+srv://tanchohang:7YTqMBWaUciSyjzY@cluster0.id5shyp.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=def0090101023d3e3db77a864ae028538963352b70da7c2cc63924a0f011b40d0f904fbab3b0d7d2611b9aacf277f8ab2a7d284a822ec9770b0448c6bc06bdcf
      - REFRESH_JWT_SECRET=2721fc5c639824baf8062bc412b81c1ce54a3da55a9c23d13df414865bc1f7d42becff2e55b74ba85be9d93acbb54a8530fb46fc214f54a17bf55d504f1d2483

      - NODE_ENV=development
      - BASE_URL=http://localhost
    user: "node:node"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app

  client:
    image: client-dev-i
    container_name: client-dev-c
    restart: unless-stopped
    build:
      context: ../keepup-client
      dockerfile: Dockerfile.dev
    ports:
      - 4173:4173
      
    environment:
      - VITE_API_URL=/api
      - VITE_MODE=development
      - NODE_ENV=development
    volumes:
      - /usr/app/node_modules
      - ../keepup-client:/usr/app
  nginx:
    depends_on:
      - client
      - api
    image: nginx-dev-i
    container_name: nginx-dev-c
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 443:443
    volumes:
        # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt:/etc/letsencrypt/
